const ingredients: Ingredient[] = [
    { "name": "Chicken breast", "category": "Meat" },
    { "name": "Salmon", "category": "Seafood" },
    { "name": "Rice", "category": "Grain" },
    { "name": "Black beans", "category": "Legumes" },
    { "name": "Carrots", "category": "Vegetables" },
    { "name": "Apples", "category": "Fruits" },
    { "name": "Milk", "category": "Dairy" },
    { "name": "Eggs", "category": "Dairy" },
    { "name": "Olive oil", "category": "Oils" },
    { "name": "Salt", "category": "Spices" },
    { "name": "Pepper", "category": "Spices" },
    { "name": "Garlic", "category": "Vegetables" },
    { "name": "Onions", "category": "Vegetables" },
    { "name": "Paprika", "category": "Spices" },
    { "name": "Basil", "category": "Herbs" },
    { "name": "Thyme", "category": "Herbs" },
    { "name": "Rosemary", "category": "Herbs" },
    { "name": "Cumin", "category": "Spices" },
    { "name": "Chili powder", "category": "Spices" },
    { "name": "Lemon", "category": "Fruits" },
    { "name": "Lime", "category": "Fruits" },
    { "name": "Oranges", "category": "Fruits" },
    { "name": "Tomatoes", "category": "Fruits" },
    { "name": "Spinach", "category": "Vegetables" },
    { "name": "Lettuce", "category": "Vegetables" },
    { "name": "Cucumber", "category": "Vegetables" },
    { "name": "Bell peppers", "category": "Vegetables" },
    { "name": "Broccoli", "category": "Vegetables" },
    { "name": "Mushrooms", "category": "Vegetables" },
    { "name": "Zucchini", "category": "Vegetables" },
    { "name": "Potatoes", "category": "Vegetables" },
    { "name": "Sweet potatoes", "category": "Vegetables" },
    { "name": "Beef", "category": "Meat" },
    { "name": "Pork", "category": "Meat" },
    { "name": "Turkey", "category": "Meat" },
    { "name": "Tofu", "category": "Vegetarian Protein" },
    { "name": "Tempeh", "category": "Vegetarian Protein" },
    { "name": "Lentils", "category": "Legumes" },
    { "name": "Chickpeas", "category": "Legumes" },
    { "name": "Quinoa", "category": "Grain" },
    { "name": "Oats", "category": "Grain" },
    { "name": "Wheat flour", "category": "Grain" },
    { "name": "Almond flour", "category": "Grain" },
    { "name": "Butter", "category": "Dairy" },
    { "name": "Cheese", "category": "Dairy" },
    { "name": "Yogurt", "category": "Dairy" },
    { "name": "Almonds", "category": "Nuts" },
    { "name": "Peanuts", "category": "Nuts" },
    { "name": "Walnuts", "category": "Nuts" },
    { "name": "Cashews", "category": "Nuts" },
    { "name": "Avocado", "category": "Fruits" },
    { "name": "Coconut oil", "category": "Oils" },
    { "name": "Sesame oil", "category": "Oils" },
    { "name": "Canola oil", "category": "Oils" },
    { "name": "Sunflower oil", "category": "Oils" },
    { "name": "Grapeseed oil", "category": "Oils" },
    { "name": "Walnut oil", "category": "Oils" },
    { "name": "Flaxseed oil", "category": "Oils" },
    { "name": "Pumpkin seeds", "category": "Seeds" },
    { "name": "Sunflower seeds", "category": "Seeds" },
    { "name": "Chia seeds", "category": "Seeds" },
    { "name": "Flaxseeds", "category": "Seeds" },
    { "name": "Sesame seeds", "category": "Seeds" },
    { "name": "Poppy seeds", "category": "Seeds" },
    { "name": "Hemp seeds", "category": "Seeds" },
    { "name": "Mustard seeds", "category": "Spices" },
    { "name": "Coriander seeds", "category": "Spices" },
    { "name": "Fennel seeds", "category": "Spices" },
    { "name": "Dill seeds", "category": "Spices" },
    { "name": "Cardamom", "category": "Spices" },
    { "name": "Clove", "category": "Spices" },
    { "name": "Nutmeg", "category": "Spices" },
    { "name": "Mace", "category": "Spices" },
    { "name": "Allspice", "category": "Spices" },
    { "name": "Saffron", "category": "Spices" },
    { "name": "Turmeric", "category": "Spices" },
    { "name": "Ginger", "category": "Spices" },
    { "name": "Horseradish", "category": "Spices" },
    { "name": "Cayenne pepper", "category": "Spices" },
    { "name": "Red pepper flakes", "category": "Spices" },
    { "name": "Parsley", "category": "Herbs" },
    { "name": "Cilantro", "category": "Herbs" },
    { "name": "Dill", "category": "Herbs" },
    { "name": "Mint", "category": "Herbs" },
    { "name": "Oregano", "category": "Herbs" },
    { "name": "Sage", "category": "Herbs" },
    { "name": "Tarragon", "category": "Herbs" },
    { "name": "Marjoram", "category": "Herbs" },
    { "name": "Chervil", "category": "Herbs" },
    { "name": "Lemongrass", "category": "Herbs" },
    { "name": "Bay leaves", "category": "Herbs" },
    { "name": "Curry leaves", "category": "Herbs" },
    { "name": "Kaffir lime leaves", "category": "Herbs" },
    { "name": "Bok choy", "category": "Vegetables" },
    { "name": "Arugula", "category": "Vegetables" },
    { "name": "Kale", "category": "Vegetables" },
    { "name": "Swiss chard", "category": "Vegetables" },
    { "name": "Collard greens", "category": "Vegetables" },
    { "name": "Mustard greens", "category": "Vegetables" },
    { "name": "Watercress", "category": "Vegetables" },
    { "name": "Parmesan cheese", "category": "Dairy" },
    { "name": "Mozzarella cheese", "category": "Dairy" },
    { "name": "Cheddar cheese", "category": "Dairy" },
    { "name": "Goat cheese", "category": "Dairy" },
    { "name": "Ricotta cheese", "category": "Dairy" },
    { "name": "Feta cheese", "category": "Dairy" },
    { "name": "Gouda cheese", "category": "Dairy" },
    { "name": "Blue cheese", "category": "Dairy" },
    { "name": "Camembert cheese", "category": "Dairy" },
    { "name": "Brie cheese", "category": "Dairy" },
    { "name": "Sour cream", "category": "Dairy" },
    { "name": "Cottage cheese", "category": "Dairy" },
    { "name": "Cream cheese", "category": "Dairy" },
    { "name": "Ghee", "category": "Dairy" },
    { "name": "Heavy cream", "category": "Dairy" },
    { "name": "Buttermilk", "category": "Dairy" },
    { "name": "Shrimp", "category": "Seafood" },
    { "name": "Crab", "category": "Seafood" },
    { "name": "Lobster", "category": "Seafood" },
    { "name": "Mussels", "category": "Seafood" },
    { "name": "Oysters", "category": "Seafood" },
    { "name": "Clams", "category": "Seafood" },
    { "name": "Squid", "category": "Seafood" },
    { "name": "Octopus", "category": "Seafood" },
    { "name": "Cod", "category": "Seafood" },
    { "name": "Tilapia", "category": "Seafood" },
    { "name": "Haddock", "category": "Seafood" },
    { "name": "Halibut", "category": "Seafood" },
    { "name": "Trout", "category": "Seafood" },
    { "name": "Mackerel", "category": "Seafood" },
    { "name": "Sardines", "category": "Seafood" },
    { "name": "Anchovies", "category": "Seafood" },
    { "name": "Tuna", "category": "Seafood" },
    { "name": "Salmon roe", "category": "Seafood" },
    { "name": "Caviar", "category": "Seafood" },
    { "name": "Pomegranate", "category": "Fruits" },
    { "name": "Mango", "category": "Fruits" },
    { "name": "Papaya", "category": "Fruits" },
    { "name": "Kiwi", "category": "Fruits" },
    { "name": "Pineapple", "category": "Fruits" },
    { "name": "Coconut", "category": "Fruits" },
    { "name": "Banana", "category": "Fruits" },
    { "name": "Dates", "category": "Fruits" },
    { "name": "Figs", "category": "Fruits" },
    { "name": "Raspberries", "category": "Fruits" },
    { "name": "Blackberries", "category": "Fruits" },
    { "name": "Blueberries", "category": "Fruits" },
    { "name": "Strawberries", "category": "Fruits" },
    { "name": "Cherries", "category": "Fruits" },
    { "name": "Peaches", "category": "Fruits" },
    { "name": "Soy sauce", "category": "Condiments" },
    { "name": "Fish sauce", "category": "Condiments" },
    { "name": "Oyster sauce", "category": "Condiments" },
    { "name": "Hoisin sauce", "category": "Condiments" },
    { "name": "Sesame seeds", "category": "Spices" },
    { "name": "Szechuan peppercorns", "category": "Spices" },
    { "name": "Star anise", "category": "Spices" },
    { "name": "Five-spice powder", "category": "Spices" },
    { "name": "Gochujang (Korean chili paste)", "category": "Condiments" },
    { "name": "Doenjang (Korean soybean paste)", "category": "Condiments" },
    { "name": "Mirin (sweet rice wine)", "category": "Condiments" },
    { "name": "Rice vinegar", "category": "Condiments" },
    { "name": "Sake", "category": "Beverages" },
    { "name": "Dashi (Japanese soup stock)", "category": "Bases" },
    { "name": "Tamarind paste", "category": "Condiments" },
    { "name": "Lemongrass", "category": "Herbs" },
    { "name": "Galangal", "category": "Spices" },
    { "name": "Kaffir lime leaves", "category": "Herbs" },
    { "name": "Thai basil", "category": "Herbs" },
    { "name": "Pandan leaves", "category": "Herbs" },
    { "name": "Daikon radish", "category": "Vegetables" },
    { "name": "Bok choy", "category": "Vegetables" },
    { "name": "Napa cabbage", "category": "Vegetables" },
    { "name": "Shiitake mushrooms", "category": "Vegetables" },
    { "name": "Enoki mushrooms", "category": "Vegetables" },
    { "name": "Wood ear mushrooms", "category": "Vegetables" },
    { "name": "Lotus root", "category": "Vegetables" },
    { "name": "Water chestnuts", "category": "Vegetables" },
    { "name": "Bamboo shoots", "category": "Vegetables" },
    { "name": "Bean sprouts", "category": "Vegetables" },
    { "name": "Kimchi", "category": "Fermented foods" },
    { "name": "Miso", "category": "Fermented foods" },
    { "name": "Tempeh", "category": "Fermented foods" },
    { "name": "Nori (seaweed)", "category": "Seafood" },
    { "name": "Wakame (seaweed)", "category": "Seafood" },
    { "name": "Dried shrimps", "category": "Seafood" },
    { "name": "Rice noodles", "category": "Grains" },
    { "name": "Udon noodles", "category": "Grains" },
    { "name": "Soba noodles", "category": "Grains" },
    { "name": "Ramen noodles", "category": "Grains" },
    { "name": "Jasmine rice", "category": "Grains" },
    { "name": "Sticky rice", "category": "Grains" },
    { "name": "Sushi rice", "category": "Grains" },
    { "name": "Black rice", "category": "Grains" },
    { "name": "Red bean paste", "category": "Condiments" },
    { "name": "Green tea powder (Matcha)", "category": "Beverages" },
    { "name": "Silken tofu", "category": "Proteins" },
    { "name": "Firm tofu", "category": "Proteins" },
    { "name": "Dried tofu", "category": "Proteins" },
    { "name": "Tofu skin (Yuba)", "category": "Proteins" },
    { "name": "Yuzu (Japanese citrus)", "category": "Fruits" },
    { "name": "Mangosteen", "category": "Fruits" },
    { "name": "Durian", "category": "Fruits" },
    { "name": "Longan", "category": "Fruits" },
    { "name": "Lychee", "category": "Fruits" },
    { "name": "Rambutan", "category": "Fruits" },
    { "name": "Dragon fruit", "category": "Fruits" },
    { "name": "Jackfruit", "category": "Fruits" },
    { "name": "Taro root", "category": "Vegetables" },
    { "name": "Edamame (soybeans)", "category": "Vegetables" },
    { "name": "Gai lan (Chinese broccoli)", "category": "Vegetables" },
    { "name": "Choy sum", "category": "Vegetables" },
    { "name": "Mung bean sprouts", "category": "Vegetables" },
    { "name": "Szechuan buttons (flower buds)", "category": "Herbs" },
    { "name": "Thai chilies", "category": "Spices" },
    { "name": "Bird's eye chili", "category": "Spices" },
    { "name": "Galangal", "category": "Spices" },
    { "name": "Shaoxing wine", "category": "Beverages" },
    { "name": "Thai fish sauce", "category": "Condiments" },
    { "name": "Plum sauce", "category": "Condiments" },
    { "name": "Sweet chili sauce", "category": "Condiments" },
    { "name": "Rice paper", "category": "Grains" },
    { "name": "Glass noodles (cellophane noodles)", "category": "Grains" },
    { "name": "Rice flour", "category": "Grains" },
    { "name": "Tapioca pearls", "category": "Grains" },
    { "name": "Szechuan chili oil", "category": "Condiments" },
    { "name": "Fermented black beans", "category": "Condiments" },
    { "name": "Korean red pepper flakes (Gochugaru)", "category": "Spices" },
    { "name": "Korean pear", "category": "Fruits" },
    { "name": "Chinese black vinegar", "category": "Condiments" },
    { "name": "Pickled ginger", "category": "Condiments" },
    { "name": "Wasabi", "category": "Condiments" },
    { "name": "Mochi", "category": "Sweets" },
    { "name": "Anko (red bean paste)", "category": "Sweets" },
    { "name": "Matcha (green tea powder)", "category": "Spices" },
    { "name": "Soybean paste (Miso)", "category": "Condiments" },
    { "name": "Bean thread noodles", "category": "Grains" },
    { "name": "Korean rice cakes (Tteok)", "category": "Grains" },
    { "name": "Japanese curry powder", "category": "Spices" },
    { "name": "Bonito flakes", "category": "Seafood" },
    { "name": "Umeboshi (pickled plums)", "category": "Fruits" },
    { "name": "Yamaimo (Japanese mountain yam)", "category": "Vegetables" },
    { "name": "Satoimo (taro root)", "category": "Vegetables" },
    { "name": "Konnyaku (konjac)", "category": "Vegetables" },
    { "name": "Gobo (burdock root)", "category": "Vegetables" },
    { "name": "Natto (fermented soybeans)", "category": "Fermented foods" },
    { "name": "Kimchi", "category": "Fermented foods" },
    { "name": "Jeotgal (Korean salted seafood)", "category": "Seafood" },
    { "name": "Japanese mayonnaise", "category": "Condiments" },
    { "name": "Panko breadcrumbs", "category": "Grains" },
    { "name": "Almond milk", "category": "Dairy Alternatives" },
    { "name": "Coconut milk", "category": "Dairy Alternatives" },
    { "name": "Soy milk", "category": "Dairy Alternatives" },
    { "name": "Oat milk", "category": "Dairy Alternatives" },
    { "name": "Rice milk", "category": "Dairy Alternatives" },
    { "name": "Cashew cheese", "category": "Dairy Alternatives" },
    { "name": "Almond cheese", "category": "Dairy Alternatives" },
    { "name": "Nutritional yeast", "category": "Condiments" },
    { "name": "Tahini", "category": "Condiments" },
    { "name": "Agave syrup", "category": "Sweeteners" },
    { "name": "Maple syrup", "category": "Sweeteners" },
    { "name": "Coconut sugar", "category": "Sweeteners" },
    { "name": "Date syrup", "category": "Sweeteners" },
    { "name": "Stevia", "category": "Sweeteners" },
    { "name": "Chickpea flour", "category": "Grains" },
    { "name": "Buckwheat", "category": "Grains" },
    { "name": "Amaranth", "category": "Grains" },
    { "name": "Teff", "category": "Grains" },
    { "name": "Spelt", "category": "Grains" },
    { "name": "Farro", "category": "Grains" },
    { "name": "Freekeh", "category": "Grains" },
    { "name": "Kamut", "category": "Grains" },
    { "name": "Millet", "category": "Grains" },
    { "name": "Sorghum", "category": "Grains" },
    { "name": "Barley", "category": "Grains" },
    { "name": "Quinoa flakes", "category": "Grains" },
    { "name": "Chia flour", "category": "Grains" },
    { "name": "Flax meal", "category": "Grains" },
    { "name": "Hemp milk", "category": "Dairy Alternatives" },
    { "name": "Vegan butter", "category": "Dairy Alternatives" },
    { "name": "Vegan mayo", "category": "Condiments" },
    { "name": "Seitan", "category": "Proteins" },
    { "name": "Pea protein", "category": "Proteins" },
    { "name": "Brown rice protein", "category": "Proteins" },
    { "name": "Spirulina", "category": "Superfoods" },
    { "name": "Chlorella", "category": "Superfoods" },
    { "name": "Maca powder", "category": "Superfoods" },
    { "name": "Cacao nibs", "category": "Superfoods" },
    { "name": "Goji berries", "category": "Superfoods" },
    { "name": "Acai powder", "category": "Superfoods" },
    { "name": "Turmeric powder", "category": "Spices" },
    { "name": "Matcha powder", "category": "Teas" },
    { "name": "Arrowroot powder", "category": "Thickeners" },
    { "name": "Agar agar", "category": "Thickeners" },
    { "name": "Guar gum", "category": "Thickeners" },
    { "name": "Xanthan gum", "category": "Thickeners" },
    { "name": "Psyllium husk", "category": "Fiber" },
    { "name": "Black salt (Kala Namak)", "category": "Spices" },
    { "name": "Smoked paprika", "category": "Spices" },
    { "name": "Liquid smoke", "category": "Flavorings" },
    { "name": "Portobello mushrooms", "category": "Vegetables" },
    { "name": "Cremini mushrooms", "category": "Vegetables" },
    { "name": "Morel mushrooms", "category": "Vegetables" },
    { "name": "Chanterelle mushrooms", "category": "Vegetables" },
    { "name": "Porcini mushrooms", "category": "Vegetables" },
    { "name": "Oyster mushrooms", "category": "Vegetables" },
    { "name": "King oyster mushrooms", "category": "Vegetables" },
    { "name": "Shimeji mushrooms", "category": "Vegetables" },
    { "name": "Enokitake mushrooms", "category": "Vegetables" },
    { "name": "Beech mushrooms", "category": "Vegetables" },
    { "name": "Maitake mushrooms", "category": "Vegetables" },
    { "name": "Truffle oil", "category": "Oils" },
    { "name": "Dried porcini mushrooms", "category": "Vegetables" },
    { "name": "Vegetable broth", "category": "Bases" },
    { "name": "Almond flour", "category": "Grains" },
    { "name": "Coconut flour", "category": "Grains" },
    { "name": "Hazelnut flour", "category": "Grains" },
    { "name": "Cassava flour", "category": "Grains" },
    { "name": "Arrowroot flour", "category": "Grains" },
    { "name": "Chickpea pasta", "category": "Grains" },
    { "name": "Lentil pasta", "category": "Grains" },
    { "name": "Quinoa pasta", "category": "Grains" },
    { "name": "Brown rice pasta", "category": "Grains" },
    { "name": "Kombu seaweed", "category": "Vegetables" },
    { "name": "Irish moss", "category": "Vegetables" },
    { "name": "Dulse", "category": "Vegetables" },
    { "name": "Nori sheets", "category": "Vegetables" },
    { "name": "Apple cider vinegar", "category": "Condiments" },
    { "name": "Balsamic vinegar", "category": "Condiments" },
    { "name": "White wine vinegar", "category": "Condiments" },
    { "name": "Red wine vinegar", "category": "Condiments" },
    { "name": "Rice vinegar", "category": "Condiments" },
    { "name": "Champagne vinegar", "category": "Condiments" },
    { "name": "Sherry vinegar", "category": "Condiments" },
    { "name": "Ume plum vinegar", "category": "Condiments" },
    { "name": "Tamari", "category": "Condiments" },
    { "name": "Liquid aminos", "category": "Condiments" },
    { "name": "Coconut aminos", "category": "Condiments" },
    { "name": "Miso paste", "category": "Condiments" },
    { "name": "Tofu (Silken)", "category": "Proteins" },
    { "name": "Tofu (Firm)", "category": "Proteins" },
    { "name": "Tofu (Extra-firm)", "category": "Proteins" },
    { "name": "Tempeh", "category": "Proteins" },
    { "name": "Textured vegetable protein (TVP)", "category": "Proteins" },
    { "name": "Vegan gelatin (Agar agar)", "category": "Baking" },
    { "name": "Pectin", "category": "Baking" },
    { "name": "Acorn squash", "category": "Vegetables" },
    { "name": "Butternut squash", "category": "Vegetables" },
    { "name": "Spaghetti squash", "category": "Vegetables" },
    { "name": "Kabocha squash", "category": "Vegetables" },
    { "name": "Delicata squash", "category": "Vegetables" },
    { "name": "Romanesco broccoli", "category": "Vegetables" },
    { "name": "Purple cauliflower", "category": "Vegetables" },
    { "name": "Rainbow chard", "category": "Vegetables" },
    { "name": "Water spinach", "category": "Vegetables" },
    { "name": "Fiddlehead ferns", "category": "Vegetables" },
    { "name": "Sunchokes (Jerusalem artichokes)", "category": "Vegetables" },
    { "name": "Jicama", "category": "Vegetables" },
    { "name": "Parsnips", "category": "Vegetables" },
    { "name": "Celeriac (celery root)", "category": "Vegetables" },
    { "name": "Kohlrabi", "category": "Vegetables" },
    { "name": "Rutabaga", "category": "Vegetables" },
    { "name": "Turnips", "category": "Vegetables" },
    { "name": "Taro", "category": "Vegetables" },
    { "name": "Yuca (Cassava)", "category": "Vegetables" },
    { "name": "Plantains", "category": "Fruits" },
    { "name": "Persimmons", "category": "Fruits" },
    { "name": "Star fruit (Carambola)", "category": "Fruits" },
    { "name": "Passion fruit", "category": "Fruits" },
    { "name": "Guava", "category": "Fruits" },
    { "name": "Feijoa (Pineapple guava)", "category": "Fruits" },
    { "name": "Pawpaw (American papaya)", "category": "Fruits" },
    { "name": "Prickly pear (Cactus fruit)", "category": "Fruits" },
    { "name": "Loquat", "category": "Fruits" },
    { "name": "Quince", "category": "Fruits" },
    { "name": "Fresh figs", "category": "Fruits" },
    { "name": "Mulberries", "category": "Fruits" },
    { "name": "Gooseberries", "category": "Fruits" },
    { "name": "Elderberries", "category": "Fruits" },
    { "name": "Cranberries", "category": "Fruits" },
    { "name": "Aronia berries", "category": "Fruits" },
    { "name": "Sea buckthorn berries", "category": "Fruits" },
    { "name": "Honeyberry (Haskap)", "category": "Fruits" },
    { "name": "Lingonberries", "category": "Fruits" },
    { "name": "Miracle fruit", "category": "Fruits" },
    { "name": "Pepitas (Pumpkin seeds)", "category": "Nuts and Seeds" },
    { "name": "Sunflower seed butter", "category": "Nuts and Seeds" },
    { "name": "Hemp seeds", "category": "Nuts and Seeds" },
    { "name": "Flaxseed oil", "category": "Oils" },
    { "name": "Pumpkin seed oil", "category": "Oils" },
    { "name": "Avocado oil", "category": "Oils" },
    { "name": "Macadamia oil", "category": "Oils" },
    { "name": "Walnut oil", "category": "Oils" },
    { "name": "Safflower oil", "category": "Oils" },
    { "name": "Grape seed oil", "category": "Oils" },
    { "name": "Rice bran oil", "category": "Oils" },
    { "name": "Mustard oil", "category": "Oils" },
    { "name": "Sacha inchi oil", "category": "Oils" },
    { "name": "Pili nuts", "category": "Nuts and Seeds" },
    { "name": "Brazil nuts", "category": "Nuts and Seeds" },
    { "name": "Cannellini beans", "category": "Legumes" },
    { "name": "Borlotti beans (Cranberry beans)", "category": "Legumes" },
    { "name": "Pecorino Romano cheese", "category": "Dairy" },
    { "name": "Gorgonzola cheese", "category": "Dairy" },
    { "name": "Mascarpone", "category": "Dairy" },
    { "name": "Ricotta salata", "category": "Dairy" },
    { "name": "Grana Padano cheese", "category": "Dairy" },
    { "name": "Fontina cheese", "category": "Dairy" },
    { "name": "Taleggio cheese", "category": "Dairy" },
    { "name": "Provolone cheese", "category": "Dairy" },
    { "name": "Coppa", "category": "Meat" },
    { "name": "Prosciutto di Parma", "category": "Meat" },
    { "name": "Soppressata", "category": "Meat" },
    { "name": "Mortadella", "category": "Meat" },
    { "name": "Bresaola", "category": "Meat" },
    { "name": "Pancetta", "category": "Meat" },
    { "name": "Guanciale", "category": "Meat" },
    { "name": "Lardo", "category": "Meat" },
    { "name": "San Marzano tomatoes", "category": "Vegetables" },
    { "name": "Porcini mushrooms", "category": "Vegetables" },
    { "name": "Arborio rice", "category": "Grains" },
    { "name": "Carnaroli rice", "category": "Grains" },
    { "name": "Vialone Nano rice", "category": "Grains" },
    { "name": "Farro", "category": "Grains" },
    { "name": "Polenta", "category": "Grains" },
    { "name": "Semolina flour", "category": "Grains" },
    { "name": "00 Flour", "category": "Grains" },
    { "name": "Fregola", "category": "Pasta" },
    { "name": "Orecchiette", "category": "Pasta" },
    { "name": "Pappardelle", "category": "Pasta" },
    { "name": "Cavatelli", "category": "Pasta" },
    { "name": "Tagliatelle", "category": "Pasta" },
    { "name": "Trofie", "category": "Pasta" },
    { "name": "Gnocchi", "category": "Pasta" },
    { "name": "Radicchio", "category": "Vegetables" },
    { "name": "Treviso", "category": "Vegetables" },
    { "name": "Fennel", "category": "Vegetables" },
    { "name": "Artichokes", "category": "Vegetables" },
    { "name": "Capers", "category": "Condiments" },
    { "name": "Anchovy fillets", "category": "Seafood" },
    { "name": "Squid ink", "category": "Condiments" },
    { "name": "Bottarga", "category": "Seafood" },
    { "name": "Truffles", "category": "Vegetables" },
    { "name": "Sage", "category": "Herbs" },
    { "name": "Rosemary", "category": "Herbs" },
    { "name": "Basil", "category": "Herbs" },
    { "name": "Oregano", "category": "Herbs" },
    { "name": "Thyme", "category": "Herbs" },
    { "name": "Marjoram", "category": "Herbs" },
    { "name": "Bay leaves", "category": "Herbs" }
]

export { ingredients };